create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,role text not null default 'staff' check(role in('owner','manager','staff')),active boolean not null default true,created_at timestamptz default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(),sku text unique not null,name text not null,brand text,category text,stock numeric not null default 0,min_stock numeric not null default 0,cost numeric not null default 0,price numeric not null default 0,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.customers(id bigint generated by default as identity primary key,name text not null,phone text,address text,created_at timestamptz default now());
create table if not exists public.cars(id bigint generated by default as identity primary key,customer_id bigint references public.customers(id) on delete set null,plate text not null,brand text,model text,created_at timestamptz default now());
create table if not exists public.sales(id uuid primary key default gen_random_uuid(),invoice_no text unique not null,customer_id bigint references public.customers(id) on delete set null,car_id bigint references public.cars(id) on delete set null,subtotal numeric not null default 0,discount numeric not null default 0,total numeric not null default 0,paid numeric not null default 0,change numeric not null default 0,sold_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.sale_items(id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.sales(id) on delete cascade,product_id uuid not null references public.products(id),qty numeric not null,cost numeric not null,price numeric not null,profit numeric generated always as((price-cost)*qty)stored);
create table if not exists public.expenses(id uuid primary key default gen_random_uuid(),title text not null,category text,amount numeric not null,note text,created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.stock_movements(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id),qty numeric not null,movement_type text not null check(movement_type in('in','out','adjust')),ref_id uuid,note text,created_by uuid references auth.users(id),created_at timestamptz default now());
alter table public.profiles enable row level security;alter table public.products enable row level security;alter table public.customers enable row level security;alter table public.cars enable row level security;alter table public.sales enable row level security;alter table public.sale_items enable row level security;alter table public.expenses enable row level security;alter table public.stock_movements enable row level security;
create policy "auth products" on public.products for all to authenticated using(true) with check(true);
create policy "auth customers" on public.customers for all to authenticated using(true) with check(true);
create policy "auth cars" on public.cars for all to authenticated using(true) with check(true);
create policy "auth sales" on public.sales for all to authenticated using(true) with check(true);
create policy "auth sale items" on public.sale_items for all to authenticated using(true) with check(true);
create policy "auth expenses" on public.expenses for all to authenticated using(true) with check(true);
create policy "auth stock movements" on public.stock_movements for all to authenticated using(true) with check(true);
create policy "own profile" on public.profiles for select to authenticated using(id=auth.uid());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name,role)values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),'owner');return new;end$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.create_sale(p_invoice_no text,p_customer_id bigint,p_car_id bigint,p_discount numeric,p_paid numeric,p_items jsonb)returns uuid language plpgsql security definer set search_path=public as $$
declare v_sale uuid;v_sub numeric:=0;v_total numeric;it jsonb;p public.products%rowtype;q numeric;
begin
for it in select * from jsonb_array_elements(p_items) loop select * into p from public.products where id=(it->>'product_id')::uuid for update;q=(it->>'qty')::numeric;if p.id is null or p.stock<q then raise exception 'สินค้าไม่พอในสต็อก';end if;v_sub:=v_sub+p.price*q;end loop;
v_total=greatest(v_sub-coalesce(p_discount,0),0);
insert into public.sales(invoice_no,customer_id,car_id,subtotal,discount,total,paid,change,sold_by)values(p_invoice_no,p_customer_id,p_car_id,v_sub,coalesce(p_discount,0),v_total,coalesce(p_paid,0),greatest(coalesce(p_paid,0)-v_total,0),auth.uid())returning id into v_sale;
for it in select * from jsonb_array_elements(p_items) loop select * into p from public.products where id=(it->>'product_id')::uuid for update;q=(it->>'qty')::numeric;insert into public.sale_items(sale_id,product_id,qty,cost,price)values(v_sale,p.id,q,p.cost,p.price);update public.products set stock=stock-q,updated_at=now()where id=p.id;insert into public.stock_movements(product_id,qty,movement_type,ref_id,created_by,note)values(p.id,-q,'out',v_sale,auth.uid(),'ขายสินค้า');end loop;return v_sale;end$$;
create or replace function public.receive_stock(p_product_id uuid,p_qty numeric,p_note text default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid;
begin
 if p_qty<=0 then raise exception 'จำนวนต้องมากกว่า 0'; end if;
 update public.products set stock=stock+p_qty,updated_at=now() where id=p_product_id returning id into v_id;
 if v_id is null then raise exception 'ไม่พบสินค้า'; end if;
 insert into public.stock_movements(product_id,qty,movement_type,created_by,note) values(p_product_id,p_qty,'in',auth.uid(),coalesce(p_note,'รับสินค้าเข้า'));
 return v_id;
end$$;

create table if not exists public.audit_logs(
 id uuid primary key default gen_random_uuid(),
 user_id uuid references auth.users(id),
 action text not null,
 entity text,
 entity_id uuid,
 details jsonb,
 created_at timestamptz default now()
);
alter table public.audit_logs enable row level security;
create policy "auth audit logs" on public.audit_logs for select to authenticated using(true);

create or replace function public.my_role()
returns text language sql stable security definer set search_path=public as $$
 select role from public.profiles where id=auth.uid() and active=true limit 1;
$$;

-- Optional stricter policies can be enabled after confirming the owner account.

create or replace view public.daily_sales_summary as
select date(created_at) as sale_date,count(*) as orders,sum(total) as sales
from public.sales group by date(created_at) order by sale_date desc;

create or replace view public.monthly_sales_summary as
select date_trunc('month',created_at)::date as month,count(*) as orders,sum(total) as sales
from public.sales group by 1 order by month desc;

create table if not exists public.daily_closings(
 id uuid primary key default gen_random_uuid(),
 closing_date date not null unique,
 cash_sales numeric not null default 0,
 expense_total numeric not null default 0,
 note text,
 closed_by uuid references auth.users(id),
 created_at timestamptz default now()
);
alter table public.daily_closings enable row level security;
create policy "auth daily closings" on public.daily_closings for all to authenticated using(true) with check(true);

create or replace view public.daily_profit_summary as
select date(s.created_at) as sale_date,
 count(distinct s.id) as orders,
 coalesce(sum(s.total),0) as sales,
 coalesce(sum(si.cost*si.qty),0) as cost,
 coalesce(sum(si.profit),0) as gross_profit
from public.sales s left join public.sale_items si on si.sale_id=s.id
group by date(s.created_at) order by sale_date desc;

-- v11: stricter role-aware policies
drop policy if exists "auth products" on public.products;
drop policy if exists "auth customers" on public.customers;
drop policy if exists "auth cars" on public.cars;
drop policy if exists "auth sales" on public.sales;
drop policy if exists "auth sale items" on public.sale_items;
drop policy if exists "auth expenses" on public.expenses;
drop policy if exists "auth stock movements" on public.stock_movements;
drop policy if exists "auth daily closings" on public.daily_closings;

create policy "products read" on public.products for select to authenticated using(true);
create policy "products write" on public.products for insert to authenticated with check(public.my_role() in ('owner','manager'));
create policy "products update" on public.products for update to authenticated using(public.my_role() in ('owner','manager')) with check(public.my_role() in ('owner','manager'));
create policy "products delete" on public.products for delete to authenticated using(public.my_role()='owner');

create policy "customers read" on public.customers for select to authenticated using(true);
create policy "customers write" on public.customers for insert to authenticated with check(public.my_role() in ('owner','manager','staff'));
create policy "customers update" on public.customers for update to authenticated using(public.my_role() in ('owner','manager','staff')) with check(public.my_role() in ('owner','manager','staff'));
create policy "customers delete" on public.customers for delete to authenticated using(public.my_role() in ('owner','manager'));

create policy "cars read" on public.cars for select to authenticated using(true);
create policy "cars write" on public.cars for insert to authenticated with check(public.my_role() in ('owner','manager','staff'));
create policy "cars update" on public.cars for update to authenticated using(public.my_role() in ('owner','manager','staff')) with check(public.my_role() in ('owner','manager','staff'));
create policy "cars delete" on public.cars for delete to authenticated using(public.my_role() in ('owner','manager'));

create policy "sales read" on public.sales for select to authenticated using(public.my_role() in ('owner','manager','staff'));
create policy "sales insert" on public.sales for insert to authenticated with check(public.my_role() in ('owner','manager','staff'));
create policy "sale items read" on public.sale_items for select to authenticated using(public.my_role() in ('owner','manager','staff'));
create policy "sale items insert" on public.sale_items for insert to authenticated with check(public.my_role() in ('owner','manager','staff'));

create policy "expenses read" on public.expenses for select to authenticated using(public.my_role() in ('owner','manager'));
create policy "expenses write" on public.expenses for insert to authenticated with check(public.my_role() in ('owner','manager'));
create policy "stock movements read" on public.stock_movements for select to authenticated using(public.my_role() in ('owner','manager','staff'));
create policy "daily closings read" on public.daily_closings for select to authenticated using(public.my_role() in ('owner','manager'));
create policy "daily closings insert" on public.daily_closings for insert to authenticated with check(public.my_role() in ('owner','manager'));

-- Only owner can change employee roles directly.
drop policy if exists "own profile" on public.profiles;
create policy "profile read self or manager" on public.profiles for select to authenticated using(id=auth.uid() or public.my_role() in ('owner','manager'));
create policy "owner update profiles" on public.profiles for update to authenticated using(public.my_role()='owner') with check(public.my_role()='owner');

-- Critical stock operations remain transactional through SECURITY DEFINER RPCs.
revoke all on function public.create_sale(text,bigint,bigint,numeric,numeric,jsonb) from public;
grant execute on function public.create_sale(text,bigint,bigint,numeric,numeric,jsonb) to authenticated;
revoke all on function public.receive_stock(uuid,numeric,text) from public;
grant execute on function public.receive_stock(uuid,numeric,text) to authenticated;

-- V3 multi-currency + reporting + employee management migration
alter table public.products add column if not exists currency text not null default 'THB' check(currency in('THB','LAK','USD'));
alter table public.sales add column if not exists currency text not null default 'THB' check(currency in('THB','LAK','USD'));
alter table public.sales add column if not exists exchange_rate numeric not null default 1;
alter table public.expenses add column if not exists currency text not null default 'THB' check(currency in('THB','LAK','USD'));
alter table public.expenses add column if not exists exchange_rate numeric not null default 1;
alter table public.profiles add column if not exists email text;

create or replace function public.create_sale_v2(p_invoice_no text,p_customer_id bigint,p_car_id bigint,p_discount numeric,p_paid numeric,p_currency text,p_items jsonb)returns uuid language plpgsql security definer set search_path=public as $$
declare v_sale uuid;v_sub numeric:=0;v_total numeric;it jsonb;p public.products%rowtype;q numeric;v_price numeric;v_cost numeric;v_rate numeric:=1;
begin
 if p_currency not in('THB','LAK','USD') then raise exception 'สกุลเงินไม่ถูกต้อง'; end if;
 for it in select * from jsonb_array_elements(p_items) loop
  select * into p from public.products where id=(it->>'product_id')::uuid for update;
  q=(it->>'qty')::numeric; v_price=coalesce((it->>'price')::numeric,p.price); v_cost=coalesce((it->>'cost')::numeric,p.cost);
  if p.id is null or p.stock<q then raise exception 'สินค้าไม่พอในสต็อก'; end if;
  v_sub:=v_sub+v_price*q;
 end loop;
 v_total=greatest(v_sub-coalesce(p_discount,0),0);
 insert into public.sales(invoice_no,customer_id,car_id,subtotal,discount,total,paid,change,sold_by,currency,exchange_rate) values(p_invoice_no,p_customer_id,p_car_id,v_sub,coalesce(p_discount,0),v_total,coalesce(p_paid,0),greatest(coalesce(p_paid,0)-v_total,0),auth.uid(),p_currency,1) returning id into v_sale;
 for it in select * from jsonb_array_elements(p_items) loop
  select * into p from public.products where id=(it->>'product_id')::uuid for update; q=(it->>'qty')::numeric; v_price=coalesce((it->>'price')::numeric,p.price); v_cost=coalesce((it->>'cost')::numeric,p.cost);
  insert into public.sale_items(sale_id,product_id,qty,cost,price) values(v_sale,p.id,q,v_cost,v_price);
  update public.products set stock=stock-q,updated_at=now() where id=p.id;
  insert into public.stock_movements(product_id,qty,movement_type,ref_id,created_by,note) values(p.id,-q,'out',v_sale,auth.uid(),'ขายสินค้า');
 end loop;
 return v_sale;
end$$;

-- Keep employee email synchronized for new users and make the first created profile the owner only when no owner exists.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,full_name,email,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email,case when not exists(select 1 from public.profiles where role='owner') then 'owner' else 'staff' end)
 on conflict(id) do update set email=excluded.email;
 return new;
end$$;
revoke all on function public.create_sale_v2(text,bigint,bigint,numeric,numeric,text,jsonb) from public;
revoke all on function public.create_sale_v2(text,bigint,bigint,numeric,numeric,text,numeric,jsonb) from public;
grant execute on function public.create_sale_v2(text,bigint,bigint,numeric,numeric,text,numeric,jsonb) to authenticated;
